<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <script>
      try {
        const array = new Array(999999999999999)
      } catch (exception) {
        console.log(exception)
        console.log()
        console.log(`예외 이름: ${exception.name}`)
        console.log(`예외 메시지: ${exception.message}`)
      }
      /*
          RangeError: Invalid array length    at 8-2-1.html:7:23
          8-2-1.html:11 예외 이름: RangeError
          8-2-1.html:12 예외 메시지: Invalid array length      
      */
    </script>
  </head>
  <body>
  </body>
</html>

<!--
  현실에서 어떤 사건이 발생하면 '누가, 언제, 어디서, 무엇을, 어떻게, 왜'라는 정보가 생깁니다.
  프로그래밍 언어에서도 예외가 발생하면 예외와 발생된 정보를 확인할 수 있습니다. 이러한 정보를
  확인할 수 있게 해주는 것이 예외 객체(exception object)입니다.
  그런데 자바스크립트는 다른 프로그래밍 언어와 비교해서 대체적으로 예외가 거의 발생하지 않는
  프로그래밍 언어입니다. 이는 프로그램에 수많은 버그를 일으킬 수 있는 요소가 되기도 합니다.
  그래서 개발자가 예외를 강제로 발생시켜줘야 하는경우가 많습니다. 예외를 강제로 발생시킬 때
  throw 키워드를 사용합니다. throw 키워드를 이용해 예외를 어떻게 강제로 발생시킬 수 있는지
  알아보겠습니다.
-->
<!--
  예외 객체
  try catch 구문을 사용할 때 catch의 괄호 안에 입력하는 식별자가 예외 객체(exception object)
  입니다. 아무 식별자나 입력해도 괜찮지만, 일반적으로 e나 exception이라는 식별자를 사용합니다.

  try{

  } catch(exception) {  // 예외 객체입니다.

  }
  
  예외 객체가 갖고 있는 속성은 브라우저에 따라 조금씩 다릅니다. 

  예외 객체의 속성
  
  속성 이름         설명
  name              예외 이름
  message           예외 메시지

  자바스크립트의 배열 크기는 4,294,967,295까지 가능합니다.

  이후에 자바스크립트를 사용해 데스크톱 또는 모바일 애플리케이션 등을 만든다면 사용자가 애플리캐이션을
  사용하는 중 예외가 발생했을 때, 어떤 예외가 발생했는지 예외 객체의 내용을 웹 요청과 메일 등으로
  전달받을 수 있게 구현해보세요.(물론 사용자에게는 요청에 대한 동의를 구해야 합니다.) 사용자로부터 받은
  예외 객체의 내용을 기반으로 어떤 오류가 발생했는지 확인하고 대처할 수 있습니다.
-->